package de.fhws.indoor.libsmartphonesensors.sensors;

import android.app.Activity;
import android.os.SystemClock;

import de.fhws.indoor.libsmartphonesensors.ASensor;
import de.fhws.indoor.libsmartphonesensors.SensorDataInterface;
import de.fhws.indoor.libsmartphonesensors.SensorType;

/**
 * Virtual Ground-Truth sensor
 * <p>
 *     This sensor inserts the ground-truth events generated by user-interaction.
 * </p>
 * @author Toni Fetzer
 */
public class GroundTruth extends ASensor {

    public GroundTruth(SensorDataInterface sensorDataInterface, final Activity act) {
        super(sensorDataInterface);
        //empty as my soul
    }

    public void writeGroundTruth(final int groundTruthCounter, long ts){
        if (sensorDataInterface != null){
            sensorDataInterface.onData(ts, SensorType.GROUND_TRUTH, Integer.toString(groundTruthCounter));
        }
    }

    public void writeInitData(int pathID, int numGroundTruthPoints, long ts){
        if (sensorDataInterface != null){
            sensorDataInterface.onData(ts, SensorType.GROUND_TRUTH_PATH, Integer.toString(pathID) + ";" + Integer.toString(numGroundTruthPoints));
        }
    }

    @Override
    public void onResume(Activity act) {

    }

    @Override
    public void onPause(Activity act) {

    }
}
